config/routes.rb
BasicEngine::Engine.routes.draw do
  resources :cars

end

app/models/basic_engine/car.rb
module BasicEngine
  class Car < ActiveRecord::Base
  end
end

app/controllers/basic_engine/application_controller.rb
module BasicEngine
  class ApplicationController < ActionController::Base
  end
end

app/controllers/basic_engine/cars_controller.rb
module BasicEngine
  class CarsController < ApplicationController
    # GET /cars
    # GET /cars.json
    def index
      @cars = Car.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @cars }
      end
    end
  
    # GET /cars/1
    # GET /cars/1.json
    def show
      @car = Car.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @car }
      end
    end
  
    # GET /cars/new
    # GET /cars/new.json
    def new
      @car = Car.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @car }
      end
    end
  
    # GET /cars/1/edit
    def edit
      @car = Car.find(params[:id])
    end
  
    # POST /cars
    # POST /cars.json
    def create
      @car = Car.new(params[:car])
  
      respond_to do |format|
        if @car.save
          format.html { redirect_to @car, notice: 'Car was successfully created.' }
          format.json { render json: @car, status: :created, location: @car }
        else
          format.html { render action: "new" }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /cars/1
    # PUT /cars/1.json
    def update
      @car = Car.find(params[:id])
  
      respond_to do |format|
        if @car.update_attributes(params[:car])
          format.html { redirect_to @car, notice: 'Car was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /cars/1
    # DELETE /cars/1.json
    def destroy
      @car = Car.find(params[:id])
      @car.destroy
  
      respond_to do |format|
        format.html { redirect_to cars_url }
        format.json { head :ok }
      end
    end
  end
end

app/helpers/basic_engine/application_helper.rb
module BasicEngine
  module ApplicationHelper
  end
end

app/helpers/basic_engine/cars_helper.rb
module BasicEngine
  module CarsHelper
  end
end

app/views/basic_engine/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basic_engine/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/basic_engine/cars/index.html.erb
<h1>Listing cars</h1>

<table>
  <tr>
    <th>Make</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.make %></td>
    <td><%= link_to 'Show', car %></td>
    <td><%= link_to 'Edit', edit_car_path(car) %></td>
    <td><%= link_to 'Destroy', car, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Car', new_car_path %>

app/views/basic_engine/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/basic_engine/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Make:</b>
  <%= @car.make %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/BasicEngine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicEngine</title>
  <%= stylesheet_link_tag    "BasicEngine/application" %>
  <%= javascript_include_tag "BasicEngine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>